services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./node-server/src:/app/src
      - ./node-server/yarn.lock:/app/yarn.lock
      - ./node-server/package.json:/app/package.json
